### ISSUE TITLE
Autoload for documented function

### ISSUE THREAD

**Issue by canatella** [SebastianMeisel/journalctl-mode#14]
Hello,

Could you add autoloads for the function that are mentionned in the README:
 - journalctl
 - journalctl-boot
 - journalctl-unit
 - journalctl-user-unit

Without it I have to manually load the could before I can use those. Thank you!

**Comment by SebastianMeisel** [comment]
Hello,

I don't quite understand the problem yet. I have 
```
(use-package journalctl-mode
  :ensure
  )
``` 
in my init.el and all functions are provided. Is that not the case with you? What version of Emacs are you running?
Please give a little more detail.

Thanks for your feedback

Sebastian

**Comment by canatella** [comment]
I'm on 27.1. I guess there is something in your config that is triggering the loading of the file. As soon as one calls `journalct-mode` the functions are loaded. I reproduced it with the Emacs sandbox script here https://github.com/alphapapa/emacs-sandbox.sh which will start Emacs and install `journalctl-mode` with a minimal configuration:

```emacs-sandbox.sh -i journalctl-mode```
 
Then try `M-x journalctl-unit`, it won't work because the function is not marked with the `;;;###autoload` and so Emacs doesn't know about it until it has properly loaded the library. Have a look at https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html and https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html#When-to-Autoload if you are unsure what I'm talking about ;)

**Comment by SebastianMeisel** [comment]
Hello,

I just uploaded the fix. I hope it works now as intended. Would appreciate your feedback.

**Comment by SebastianMeisel** [comment]
Okay, I hope that I got I now.

**Comment by canatella** [comment]
Yes, just tested I've got all the 4 functions available now! Thanks for taking the time to add this and for writing this package :)
