### ISSUE TITLE
journalctl-user-unit broken

### ISSUE THREAD

**Issue by BenediktBroich** [SebastianMeisel/journalctl-mode#16]
The function `journalctl-user-unit` does not work. The Function adds the option "--user-unit". The Function `journalctl-parse-options` does check if `journalctl-list-of-options` contains "user-unit", but it only contains "userunit" so the option is removed.

**Comment by jkxyz** [comment]
Can be fixed locally with:

```
(require 'journalctl-mode)
(add-to-list 'journalctl-list-of-options "user-unit")
```
