### ISSUE TITLE
Please update license version in header, conflicts with LICENSE file

### ISSUE THREAD

**Issue by tarsius** [SebastianMeisel/journalctl-mode#18]
Please update the permission statement. I recommend you use the standard permission statement:

```elisp
;; This file is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published
;; by the Free Software Foundation, either version 3 of the License,
;; or (at your option) any later version.
;;
;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this file.  If not, see <https://www.gnu.org/licenses/>.
```

Additionally it would be nice if you could add a license header, for easier parsing:

```elisp
;; SPDX-License-Identifier: GPL-3.0-or-later
```

Thanks!

This will allow us to continue to distribute this package on Melpa.

/cc @riscy

**Comment by tarsius** [comment]
To be clear, the permission statement in the library currently says this is licensed under the GPLv2 (not "GPLv2 or a later version"). This is incompatible with the license used by Emacs (>= GPLv3). Please fix that so we don't have to remove this package from Melpa. Thanks!

**Comment by tarsius** [comment]
The license of elisp packages have to be compatible with that of Emacs and GPL-2.0 is not compatible with GPL-3.0. While it appears that you intended to use GPL-3.0, since you included that license file, the permission statement actually says v2, and that overrides the license file as it is more local. Please correct that soon or I will be forced to remove this package from Melpa and the Emacsmirror.

**Comment by tarsius** [comment]
I have now removed the package from Melpa.

**Comment by SebastianMeisel** [comment]
I updated the Licence file, please resubmit to melpa.

**Comment by tarsius** [comment]
Thanks!

The removal has been reverted.

**Comment by tarsius** [comment]
It seems there was a misunderstanding.

1. We can only distribute packages on Melpa whose licenses are compatible with those of GNU Emacs.
2. Emacs is released under version **3** of the GPL.
3. Previously it was *unclear* whether your package is released under version 2 or 3 of the GPL.
4. You have *clarified* that now. It is released under version **2** of the GPL.
5. Therefore the license of this package is not compatible with that of Emacs and it therefore has to removed from Melpa again.

Since you asked me to resubmit this to Melpa, I am *guessing* that this was not your intention.

If that is so, then you have to do these things.

1. Revert the change to the LICENSE file, so that it contains the text of version 3 again.
2. Remove this from `journal-mode.el`:
    ```
    ;; You can redistribute this program and/or modify it under the terms of the GNU General Public License version 
    ```
6. Add this instead:
    ```
    ;; This file is free software: you can redistribute it and/or modify
    ;; it under the terms of the GNU General Public License as published
    ;; by the Free Software Foundation, either version 3 of the License,
    ;; or (at your option) any later version.
    ;;
    ;; This file is distributed in the hope that it will be useful,
    ;; but WITHOUT ANY WARRANTY; without even the implied warranty of
    ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ;; GNU General Public License for more details.
    ;;
    ;; You should have received a copy of the GNU General Public License
    ;; along with this file.  If not, see <https://www.gnu.org/licenses/>.
    ```

If I guessed wrong, then please explicitly tell me that it is your intention to release this under the terms of version 2 of the GPL. I will then remove it from Melpa again.

**Comment by SebastianMeisel** [comment]
Hello,

sorry it took so long. I'm now back on GPL v.3 with the appropriate text in
the *.el.

Greetings

Sebastian

Am Mo., 14. Nov. 2022 um 21:19 Uhr schrieb Jonas Bernoulli <
***@***.***>:

**Comment by tarsius** [comment]
Looks good now. Thanks!
