### ISSUE TITLE
[transient] First chunk has only one line if choose unit filter

### ISSUE THREAD

**Issue by Crandel** [SebastianMeisel/journalctl-mode#21]
*version*: Emacs 29.1 with pgtk support

Every time I filter by specific unit, system or user only one line is rendering in \*journalctl\* buffer. 
Without filtering it contains 250 lines

My setup

```lisp
(use-package journalctl-mode
  :vc (:fetcher github :repo SebastianMeisel/journalctl-mode :rev "transient")
  :bind (
  ("C-c t" . journalctl)
  :map evil-normal-state-map
  ("gtt" . journalctl)
  )
)
```

**Comment by SebastianMeisel** [comment]
Thanks for reaching out. I can confirm the behavior and look into it.

**Comment by SebastianMeisel** [comment]
It's a bit strange, as it doesn't happen, when I test it with edebug. Seems to be some kind of race-condition. I added a short delay, which seems to solve the problem. Could you check if it works for you too now?

**Comment by Crandel** [comment]
Just check it again, still the same issue. If I press next chunk and previous chunk commands it will show correct output(250 lines).

BTW transient branch still not showing broken/unactive user units

**Comment by SebastianMeisel** [comment]
Okay, the second point is solved now. The first one is more difficult - weird: This problem only occurs the very first time you run journalctl in an Emacs session. (Please Confirm). That makes it very difficult to debug. I hope I find a solution...

**Comment by SebastianMeisel** [comment]
I think I found a (somewhat dirty but working) hack. Could you confirm? Make sure you `package-delete journalctl` and restart emacs to make sure, you got the newest version.

**Comment by Crandel** [comment]
Now it works, but also it loads first 250 lines journalctl output without filter applied. After applying filters everything works correctly. Was it designed like this for reason? There is small delay every time I launch journalctl mode.

**Comment by SebastianMeisel** [comment]
Well it's a hack, because still for some reason I can't figure out, it would only load 1 line on the first start. So I load it with --lines=250 once. The delay exists, because it runs journalctl asynchronously.

**Comment by Crandel** [comment]
Thank you for detailed explanation.
