### ISSUE TITLE
describe-key on various journalctl-mode keys  shows bytecodes

### ISSUE THREAD

**Issue by tvraman** [SebastianMeisel/journalctl-mode#32]
as an example, C-h c +s shows '+ s runs the command ... binary chars

**Comment by SebastianMeisel** [comment]
I cannot reproduce this. Also +s with a keybinding in an older version. Please try to update or come back, to clarify what you mean. Sorry to be of no help here.

**Comment by tvraman** [comment]
no worries -- this was related to the transient issue 
--
