### ISSUE TITLE
Bind journalctl-transient to a key

### ISSUE THREAD

**Issue by tvraman** [SebastianMeisel/journalctl-mode#33]
As a keyboard only user, it's useful to bind journalctl-transient to a key -- perhaps recommend that in the commentary section?

**Comment by SebastianMeisel** [comment]
Thanks for your input. I have included in the README as well. Sorry it took me so long.

**Comment by tvraman** [comment]
And thanks for journalctl-mode, it makes a powerful but confusing tool
easy to use.

--
